name: CI/CD Pipeline

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python -m pytest tests/

  deploy:
    needs: test # This ensures deploy only runs if tests pass
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/CommonAssessmentTool
            git pull origin main
            source venv/bin/activate
            pkill uvicorn || true
            nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &
          EOF
      
      - name: Build Docker image
        run: docker build -t common-assessment-tool .

      - name: Run Docker container
        run: |
          docker run -d -p 8000:8000 common-assessment-tool
          sleep 30  # Wait for container to start

      - name: Test Docker container
        run: |
          curl http://localhost:8000/docs
